repos:
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variables']

  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args:
          - --line-length=120
        language_version: python3.8